"""Builtin APPROVED causal feature definitions (Phase 6B initial families)."""

from __future__ import annotations

import hashlib

from data.events.enums import DataCapability, EventSchemaType
from features.catalog import FeatureCatalog
from features.contracts import (
    FeatureApprovalStatus,
    FeatureCategory,
    FeatureContract,
    MissingValuePolicy,
)


def _hash(name: str) -> str:
    return hashlib.sha256(f"feature_impl|{name}|v1".encode()).hexdigest()[:16]


def _bar_feature(
    feature_id: str,
    name: str,
    category: FeatureCategory,
    description: str,
    rationale: str,
    *,
    lookback: int,
    warm_up: int | None = None,
    units: str,
    complexity: float = 1.0,
    deps: tuple[str, ...] = (),
    requires_fit: bool = False,
    caps: tuple[DataCapability, ...] = (DataCapability.OHLCV_BARS,),
    approval: FeatureApprovalStatus = FeatureApprovalStatus.APPROVED,
) -> FeatureContract:
    warm = warm_up if warm_up is not None else lookback
    return FeatureContract(
        feature_id=feature_id,
        feature_version="1.0.0",
        feature_name=name,
        category=category,
        description=description,
        economic_rationale=rationale,
        input_event_types=(EventSchemaType.BAR,),
        source_symbols=("*",),
        permitted_asset_classes=("futures", "cfd"),
        lookback_bars=lookback,
        warm_up_bars=warm,
        update_frequency="bar",
        source_timestamp_rule="bar_open_or_event_timestamp",
        availability_timestamp_rule="bar_end",
        maximum_staleness="1d",
        missing_value_policy=MissingValuePolicy.DROP_UNTIL_WARMUP,
        output_units=units,
        causal=True,
        requires_training_fit=requires_fit,
        complexity_cost=complexity,
        dependencies=deps,
        implementation_hash=_hash(feature_id),
        approval_status=approval,
        required_capabilities=caps,
    )


def build_default_catalog() -> FeatureCatalog:
    """Register the Phase 6B initial APPROVED causal feature set."""
    cat = FeatureCatalog()
    specs: list[FeatureContract] = [
        # --- Price / returns ---
        _bar_feature(
            "price.simple_return_1",
            "simple_return_1",
            FeatureCategory.PRICE,
            "One-bar simple return close[t]/close[t-1]-1",
            "Captures short-horizon price momentum / mean-reversion input",
            lookback=1,
            units="return",
        ),
        _bar_feature(
            "price.log_return_1",
            "log_return_1",
            FeatureCategory.PRICE,
            "One-bar logarithmic return",
            "Additive log returns for compounding analysis",
            lookback=1,
            units="log_return",
        ),
        _bar_feature(
            "price.return_5",
            "return_5",
            FeatureCategory.PRICE,
            "5-bar simple return",
            "Multi-horizon lagged return",
            lookback=5,
            units="return",
            complexity=1.2,
        ),
        _bar_feature(
            "price.close_to_open",
            "close_to_open",
            FeatureCategory.PRICE,
            "Overnight gap: open[t]/close[t-1]-1",
            "Gap risk / overnight information",
            lookback=1,
            units="return",
        ),
        _bar_feature(
            "price.open_to_close",
            "open_to_close",
            FeatureCategory.PRICE,
            "Intrabar open-to-close return",
            "Session directional impulse within the bar",
            lookback=0,
            warm_up=0,
            units="return",
        ),
        _bar_feature(
            "price.hl_range",
            "hl_range",
            FeatureCategory.PRICE,
            "High-low range in price units",
            "Raw range as a liquidity / volatility proxy",
            lookback=0,
            warm_up=0,
            units="price",
        ),
        _bar_feature(
            "price.norm_body",
            "normalized_candle_body",
            FeatureCategory.PRICE,
            "(close-open)/(high-low)",
            "Directional conviction relative to total range",
            lookback=0,
            warm_up=0,
            units="ratio",
        ),
        _bar_feature(
            "price.upper_wick",
            "upper_wick_ratio",
            FeatureCategory.PRICE,
            "Upper wick / range",
            "Rejection of highs",
            lookback=0,
            warm_up=0,
            units="ratio",
        ),
        _bar_feature(
            "price.lower_wick",
            "lower_wick_ratio",
            FeatureCategory.PRICE,
            "Lower wick / range",
            "Rejection of lows",
            lookback=0,
            warm_up=0,
            units="ratio",
        ),
        _bar_feature(
            "price.dist_rolling_mean_20",
            "distance_to_rolling_mean_20",
            FeatureCategory.PRICE,
            "close / rolling_mean_20 - 1",
            "Mean-reversion distance",
            lookback=20,
            units="ratio",
        ),
        _bar_feature(
            "price.rolling_rank_20",
            "rolling_rank_20",
            FeatureCategory.PRICE,
            "Percentile rank of close in 20-bar window",
            "Relative location in recent distribution",
            lookback=20,
            units="rank",
            complexity=1.5,
        ),
        _bar_feature(
            "price.rolling_z_20",
            "rolling_zscore_20",
            FeatureCategory.PRICE,
            "20-bar rolling Z-score of close",
            "Standardized mean-reversion signal",
            lookback=20,
            units="zscore",
        ),
        _bar_feature(
            "price.breakout_distance_20",
            "breakout_distance_20",
            FeatureCategory.PRICE,
            "close / prior_rolling_max_20 - 1",
            "Distance from trailing high (upside breakout)",
            lookback=20,
            units="ratio",
        ),
        _bar_feature(
            "price.breakdown_distance_20",
            "breakdown_distance_20",
            FeatureCategory.PRICE,
            "close / prior_rolling_min_20 - 1",
            "Distance from trailing low (downside breakdown)",
            lookback=20,
            units="ratio",
        ),
        _bar_feature(
            "price.gap_size",
            "gap_size",
            FeatureCategory.PRICE,
            "open - prior close",
            "Absolute gap size",
            lookback=1,
            units="price",
        ),
        # --- VWAP / liquidity ---
        _bar_feature(
            "liq.session_vwap",
            "causal_session_vwap",
            FeatureCategory.LIQUIDITY,
            "Causal cumulative session VWAP through current bar",
            "Intraday fair-value anchor without using future session bars",
            lookback=1,
            warm_up=1,
            units="price",
            complexity=2.0,
        ),
        _bar_feature(
            "liq.dist_session_vwap",
            "distance_from_session_vwap",
            FeatureCategory.LIQUIDITY,
            "close / causal_session_vwap - 1",
            "Mean-reversion vs session VWAP",
            lookback=1,
            warm_up=1,
            units="ratio",
            deps=("liq.session_vwap",),
            complexity=2.0,
        ),
        _bar_feature(
            "liq.rolling_vwap_20",
            "rolling_vwap_20",
            FeatureCategory.LIQUIDITY,
            "20-bar rolling VWAP",
            "Shorter liquidity-weighted fair value",
            lookback=20,
            units="price",
        ),
        _bar_feature(
            "liq.volume_pct_20",
            "volume_percentile_20",
            FeatureCategory.LIQUIDITY,
            "Percentile of volume in 20-bar window",
            "Relative participation",
            lookback=20,
            units="rank",
        ),
        _bar_feature(
            "liq.rel_tod_volume",
            "causal_relative_tod_volume",
            FeatureCategory.LIQUIDITY,
            "volume / expanding same-time-of-day mean (causal)",
            "Seasonal volume anomaly without full-history leakage",
            lookback=5,
            warm_up=5,
            units="ratio",
            complexity=2.5,
        ),
        # --- Volatility ---
        _bar_feature(
            "vol.atr_14",
            "atr_14",
            FeatureCategory.VOLATILITY,
            "14-bar Average True Range",
            "Risk scaling and stop distance",
            lookback=14,
            units="price",
        ),
        _bar_feature(
            "vol.norm_atr_14",
            "normalized_atr_14",
            FeatureCategory.VOLATILITY,
            "ATR_14 / close",
            "Scale-free volatility",
            lookback=14,
            units="ratio",
            deps=("vol.atr_14",),
        ),
        _bar_feature(
            "vol.atr_pct_50",
            "atr_percentile_50",
            FeatureCategory.VOLATILITY,
            "Percentile of ATR in 50-bar window",
            "Relative volatility regime",
            lookback=50,
            units="rank",
            deps=("vol.atr_14",),
            complexity=1.5,
        ),
        _bar_feature(
            "vol.realized_20",
            "realized_volatility_20",
            FeatureCategory.VOLATILITY,
            "Std of 1-bar returns over 20 bars",
            "Realized vol estimate",
            lookback=20,
            units="volatility",
        ),
        _bar_feature(
            "vol.parkinson_20",
            "parkinson_volatility_20",
            FeatureCategory.VOLATILITY,
            "Parkinson HL-range volatility",
            "Range-based vol estimator",
            lookback=20,
            units="volatility",
            complexity=1.5,
        ),
        _bar_feature(
            "vol.range_compression_20",
            "range_compression_20",
            FeatureCategory.VOLATILITY,
            "Current range / rolling mean range",
            "Compression often precedes expansion",
            lookback=20,
            units="ratio",
        ),
        _bar_feature(
            "vol.prior_range_compression_20",
            "prior_range_compression_20",
            FeatureCategory.VOLATILITY,
            "range_compression_20.shift(1)",
            "Prior-bar compression context available before the signal bar",
            lookback=20,
            warm_up=21,
            units="ratio",
        ),
        _bar_feature(
            "vol.downside_20",
            "downside_volatility_20",
            FeatureCategory.VOLATILITY,
            "Std of negative returns only",
            "Asymmetric risk",
            lookback=20,
            units="volatility",
        ),
        _bar_feature(
            "vol.upside_20",
            "upside_volatility_20",
            FeatureCategory.VOLATILITY,
            "Std of positive returns only",
            "Upside dispersion",
            lookback=20,
            units="volatility",
        ),
        # --- Temporal (exchange-local; no fixed UTC open) ---
        _bar_feature(
            "temp.minutes_since_open",
            "minutes_since_session_open",
            FeatureCategory.TEMPORAL,
            "Minutes since exchange-local session open",
            "Intraday seasonality",
            lookback=0,
            warm_up=0,
            units="minutes",
            complexity=1.2,
        ),
        _bar_feature(
            "temp.minutes_to_close",
            "minutes_until_session_close",
            FeatureCategory.TEMPORAL,
            "Minutes until exchange-local session close",
            "End-of-session effects",
            lookback=0,
            warm_up=0,
            units="minutes",
            complexity=1.2,
        ),
        _bar_feature(
            "temp.dow",
            "day_of_week",
            FeatureCategory.TEMPORAL,
            "Exchange-local day of week (Mon=0)",
            "Calendar seasonality",
            lookback=0,
            warm_up=0,
            units="category",
        ),
        _bar_feature(
            "temp.sin_tod",
            "cyclical_time_sin",
            FeatureCategory.TEMPORAL,
            "sin(2π * minutes_since_midnight / 1440)",
            "Cyclical time encoding",
            lookback=0,
            warm_up=0,
            units="ratio",
        ),
        _bar_feature(
            "temp.cos_tod",
            "cyclical_time_cos",
            FeatureCategory.TEMPORAL,
            "cos(2π * minutes_since_midnight / 1440)",
            "Cyclical time encoding",
            lookback=0,
            warm_up=0,
            units="ratio",
        ),
        # --- Microstructure (require quotes/trades; DISABLED without caps) ---
        _bar_feature(
            "micro.quoted_spread",
            "quoted_spread",
            FeatureCategory.MICROSTRUCTURE,
            "ask - bid from quote events",
            "Transaction cost / liquidity",
            lookback=1,
            units="price",
            caps=(DataCapability.BID_ASK_QUOTES,),
            approval=FeatureApprovalStatus.APPROVED,
            complexity=2.0,
        ),
        _bar_feature(
            "micro.book_imbalance",
            "order_book_imbalance",
            FeatureCategory.MICROSTRUCTURE,
            "bid_size/(bid_size+ask_size) from book",
            "Short-term pressure",
            lookback=1,
            units="ratio",
            caps=(DataCapability.ORDER_BOOK_SNAPSHOTS,),
            approval=FeatureApprovalStatus.APPROVED,
            complexity=3.0,
        ),
        # Explicitly NOT computing true volume delta from OHLCV
        FeatureContract(
            feature_id="micro.volume_delta_ohlcv_forbidden",
            feature_version="1.0.0",
            feature_name="volume_delta_from_ohlcv",
            category=FeatureCategory.MICROSTRUCTURE,
            description="Forbidden placeholder — true volume delta cannot be derived from OHLCV",
            economic_rationale="N/A — disabled to prevent false microstructure claims",
            input_event_types=(EventSchemaType.BAR,),
            source_symbols=("*",),
            permitted_asset_classes=("futures", "cfd"),
            lookback_bars=1,
            warm_up_bars=1,
            update_frequency="bar",
            source_timestamp_rule="n/a",
            availability_timestamp_rule="n/a",
            maximum_staleness="0s",
            missing_value_policy=MissingValuePolicy.PROPAGATE_NAN,
            output_units="n/a",
            causal=False,
            requires_training_fit=False,
            complexity_cost=0.0,
            dependencies=(),
            implementation_hash=_hash("forbidden_vd"),
            approval_status=FeatureApprovalStatus.DISABLED,
            required_capabilities=(),
            notes="Do not calculate true Volume Delta from OHLCV bars.",
        ),
        # --- Cross-asset (hypothesis features; require secondary series) ---
        _bar_feature(
            "xasset.lagged_return",
            "cross_asset_lagged_return",
            FeatureCategory.CROSS_ASSET,
            "Lagged simple return of a secondary symbol",
            "Lead/lag hypothesis — not an assumed truth",
            lookback=1,
            units="return",
            complexity=2.0,
            caps=(DataCapability.OHLCV_BARS,),
        ),
        _bar_feature(
            "xasset.rolling_corr_20",
            "causal_rolling_correlation_20",
            FeatureCategory.CROSS_ASSET,
            "20-bar rolling correlation vs secondary",
            "Cross-asset co-movement hypothesis",
            lookback=20,
            units="correlation",
            complexity=2.5,
        ),
        # --- Regime ---
        _bar_feature(
            "regime.vol_of_vol_20",
            "volatility_of_volatility_20",
            FeatureCategory.REGIME,
            "Rolling std of ATR changes",
            "Regime instability",
            lookback=20,
            units="volatility",
            deps=("vol.atr_14",),
            complexity=2.0,
        ),
        _bar_feature(
            "regime.trend_state",
            "causal_trend_state",
            FeatureCategory.REGIME,
            "Causal EMA slope/separation normalized by ATR, clipped to [-1,1]. "
            "+1 strong uptrend, -1 strong downtrend, ~0 range. |x|>=0.25 trending.",
            "Executable regime gate for require_trend_regime / prefer_range_regime",
            lookback=30,
            units="regime_code",
            complexity=2.0,
        ),
        _bar_feature(
            "regime.volatility_state",
            "causal_volatility_state",
            FeatureCategory.REGIME,
            "Causal realized-vol vs rolling median, clipped to [-1,1]. "
            "+1 expansion, -1 compression, ~0 normal. x>=0.25 expansion.",
            "Executable regime gate for prefer_vol_expansion",
            lookback=40,
            units="regime_code",
            complexity=2.0,
        ),
    ]
    for spec in specs:
        cat.register(spec)
    return cat
